# Generated by Django 3.1 on 2020-08-10 12:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tasktracker',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
