# Generated by Django 3.1 on 2020-08-13 07:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_tasktracker_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tasktracker',
            name='update_type',
            field=models.CharField(choices=[('DAILY', 'DAILY'), ('WEEKLY', 'WEEKLY'), ('MONTHLY', 'MONTHLY')], default='DAILY', max_length=10),
        ),
    ]
