# Generated by Django 3.1 on 2020-08-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0003_auto_20200813_1238'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktracker',
            name='id',
        ),
        migrations.AlterField(
            model_name='tasktracker',
            name='email',
            field=models.EmailField(max_length=254, primary_key=True, serialize=False),
        ),
    ]
