# Generated by Django 3.1 on 2020-08-13 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0004_auto_20200813_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tasktracker',
            name='date',
        ),
        migrations.AddField(
            model_name='task',
            name='date',
            field=models.DateField(auto_now=True),
        ),
    ]
